name: Deploy to ECS (Stress App)

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: stress
  ECS_CLUSTER: babicluster
  ECS_SERVICE: babi123
  CONTAINER_NAME: stress
  TASK_DEFINITION_FILE: ecs-task-def.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS identity
      run: aws sts get-caller-identity

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:$IMAGE_TAG
        echo "Building image: $IMAGE_URI"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Download current task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition $ECS_SERVICE \
          --query taskDefinition > $TASK_DEFINITION_FILE
        cat $TASK_DEFINITION_FILE

    - name: Replace image in task definition
      run: |
        jq --arg IMAGE "$IMAGE_URI" \
          '.containerDefinitions[0].image = $IMAGE
          | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
          $TASK_DEFINITION_FILE > new-task-def.json
        cat new-task-def.json

    - name: Register new task definition
      id: register
      run: |
        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json \
          --query "taskDefinition.taskDefinitionArn" \
          --output text)
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
        echo "Registered task: $TASK_DEF_ARN"

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --task-definition $TASK_DEF_ARN
